import { financialDatasetSchema } from "./schemas";

export const demoWorkspaceDataset = financialDatasetSchema.parse({
	cashActions: [
		{
			description: "Aurora Health is below the collection confidence threshold before the June cash buffer dip.",
			dueDate: "2024-05-17",
			id: "action-collect-aurora",
			impactCents: 12_650_000,
			owner: "Samira Chen",
			priority: "critical",
			status: "open",
			title: "Collect Aurora Health before buffer risk",
			type: "collection",
			visibleTo: ["owner-finance", "manager"],
		},
		{
			description: "Notion trial seats are renewing with low usage. Cut them before the next monthly bill.",
			dueDate: "2024-05-20",
			id: "action-cut-notion",
			impactCents: 1_320_000,
			owner: "Finance",
			priority: "high",
			status: "open",
			title: "Cancel Notion trial seats",
			type: "vendor-leak",
			visibleTo: ["owner-finance", "manager"],
		},
		{
			description: "GitHub duplicate seats are active across two teams and should be consolidated.",
			dueDate: "2024-05-22",
			id: "action-cut-github",
			impactCents: 980_000,
			owner: "Operations",
			priority: "high",
			status: "open",
			title: "Consolidate GitHub seats",
			type: "vendor-leak",
			visibleTo: ["owner-finance", "manager"],
		},
	],
	forecast: [
		{
			date: "2024-05-20",
			id: "forecast-1",
			inflowCents: 18_000_000,
			openingBalanceCents: 220_000_000,
			outflowCents: 18_000_000,
			scenario: "base",
		},
		{
			date: "2024-05-27",
			id: "forecast-2",
			inflowCents: 68_000_000,
			openingBalanceCents: 220_000_000,
			outflowCents: 18_000_000,
			scenario: "base",
		},
		{
			date: "2024-06-03",
			id: "forecast-3",
			inflowCents: 16_000_000,
			openingBalanceCents: 270_000_000,
			outflowCents: 68_000_000,
			scenario: "base",
		},
		{
			date: "2024-06-10",
			id: "forecast-4",
			inflowCents: 10_000_000,
			openingBalanceCents: 218_000_000,
			outflowCents: 58_000_000,
			scenario: "base",
		},
		{
			date: "2024-06-17",
			id: "forecast-5",
			inflowCents: 42_000_000,
			openingBalanceCents: 170_000_000,
			outflowCents: 4_000_000,
			scenario: "base",
		},
	],
	invoices: [
		{
			amountCents: 12_650_000,
			client: "Aurora Health",
			collectionProbability: 41,
			dueDate: "2024-05-17",
			id: "invoice-aurora-health",
			owner: "Samira Chen",
			status: "overdue",
		},
		{
			amountCents: 8_700_000,
			client: "Northstar Labs",
			collectionProbability: 76,
			dueDate: "2024-05-24",
			id: "invoice-northstar-labs",
			owner: "Finance",
			status: "sent",
		},
	],
	profile: {
		cashBalanceCents: 248_000_000,
		cashBufferTargetCents: 14_000_000,
		companyId: "cashlift-demo",
		defaultRole: "owner-finance",
		industry: "consulting",
		monthlyPayrollCents: 62_000_000,
		name: "CashLift",
	},
	spendRequests: [
		{
			amountCents: 38_000,
			category: "hardware",
			id: "request-webcam",
			neededByDate: "2024-05-17",
			reason: "Replacement webcam for client calls",
			requestedDate: "2024-05-15",
			requester: "Nora Lee",
			status: "pending",
			team: "Client Delivery",
			vendor: "Logitech",
		},
	],
	subscriptions: [
		{
			amountCents: 1_320_000,
			id: "subscription-notion",
			owner: "Finance",
			renewalDate: "2024-05-20",
			status: "trial",
			usagePercent: 22,
			vendor: "Notion",
		},
		{
			amountCents: 980_000,
			id: "subscription-github",
			owner: "Operations",
			renewalDate: "2024-05-22",
			status: "duplicate",
			usagePercent: 74,
			vendor: "GitHub",
		},
	],
	teamBudgets: [
		{
			approvedCents: 9_800_000,
			committedCents: 50_000_000,
			id: "budget-client-delivery",
			monthlyBudgetCents: 66_900_000,
			team: "Client Delivery",
		},
		{
			approvedCents: 8_700_000,
			committedCents: 46_000_000,
			id: "budget-finance",
			monthlyBudgetCents: 59_600_000,
			team: "Finance",
		},
		{
			approvedCents: 7_100_000,
			committedCents: 40_000_000,
			id: "budget-operations",
			monthlyBudgetCents: 51_300_000,
			team: "Operations",
		},
	],
	teamMembers: [
		{ id: "member-samira", name: "Samira Chen", role: "owner-finance", team: "Finance" },
		{ id: "member-maya", name: "Maya Patel", role: "manager", team: "Client Delivery" },
		{ id: "member-nora", name: "Nora Lee", role: "employee", team: "Operations" },
	],
	vendorBills: [
		{
			amountCents: 3_400_000,
			category: "software",
			dueDate: "2024-05-24",
			essential: true,
			id: "vendor-bill-atlassian",
			status: "scheduled",
			vendor: "Atlassian",
		},
	],
});
